Repository kadirnar/segment-anything-video, pull requests merged in 2023-04, with the labels that each got.

#1 add main code
  MANIFEST.in
  README.md
  meta_segment/__init__.py
  meta_segment/automatic_mask_generator.py
  meta_segment/build_sam.py
  meta_segment/modeling/__init__.py
  meta_segment/modeling/common.py
  meta_segment/modeling/image_encoder.py
  meta_segment/modeling/mask_decoder.py
  meta_segment/modeling/prompt_encoder.py
  meta_segment/modeling/sam.py
  meta_segment/modeling/transformer.py
  meta_segment/predictor.py
  meta_segment/utils/__init__.py
  meta_segment/utils/amg.py
  meta_segment/utils/onnx.py
  meta_segment/utils/transforms.py
  pyproject.toml
  requirements.txt
  scripts/amg.py
  scripts/code_format.sh
  scripts/export_onnx_model.py
  scripts/package.sh
  setup.cfg
  setup.py
Labels: documentation, enhancement

#2 The package name has been changed.
  meta_segment/__init__.py
  meta_segment/modeling/__init__.py
  metaseg/__init__.py
  metaseg/automatic_mask_generator.py
  metaseg/build_sam.py
  metaseg/modeling/__init__.py
  metaseg/modeling/common.py
  metaseg/modeling/image_encoder.py
  metaseg/modeling/mask_decoder.py
  metaseg/modeling/prompt_encoder.py
  metaseg/modeling/sam.py
  metaseg/modeling/transformer.py
  metaseg/predictor.py
  metaseg/utils/__init__.py
  metaseg/utils/amg.py
  metaseg/utils/onnx.py
  metaseg/utils/transforms.py
  scripts/amg.py
  scripts/export_onnx_model.py
  setup.py
Labels: documentation, enhancement

#4 Update README.md
  README.md
Labels: documentation

#12 Add the video support and auto download checkpoint
  README.md
  metaseg/__init__.py
  metaseg/demo.py
  metaseg/utils/file.py
Labels: documentation, enhancement

#13 add the video_demo file
  README.md
Labels: documentation

#14 Update codes for web application.
  README.md
  metaseg/__init__.py
  metaseg/app.py
  metaseg/demo.py
Labels: documentation, enhancement

#15 update req.txt file
  metaseg/__init__.py
  requirements.txt
Labels: documentation

#16 Add min_area and max_area parameters.
  metaseg/__init__.py
  metaseg/app.py
  metaseg/demo.py
Labels: bug, enhancement

#17 add data_utils.py
  metaseg/demo.py
  metaseg/utils/__init__.py
  metaseg/utils/data_utils.py
  metaseg/utils/file_utils.py
Labels: enhancement

#18 min_area variable updated.
  README.md
  metaseg/app.py
  metaseg/demo.py
Labels: documentation, enhancement

#20 add manuel_mask feature
  README.md
  metaseg/__init__.py
  metaseg/auto_mask_demo.py
  metaseg/manuel_mask_demo.py
  metaseg/utils/__init__.py
  metaseg/utils/data_utils.py
  metaseg/webapp/__init__.py
  metaseg/webapp/app.py
Labels: documentation, enhancement

#25 add manuel point selection
  README.md
  metaseg/mask_predictor.py
Labels: documentation, enhancement

#26 update_version
  metaseg/__init__.py
Labels: documentation

#28 add multi boxes feature
  README.md
  metaseg/__init__.py
  metaseg/mask_predictor.py
Labels: bug, documentation, enhancement

#31 Add SAHI library
  metaseg/__init__.py
  metaseg/mask_predictor.py
  metaseg/sahi_predict.py
Labels: bug

#33 :wolf: add progress display for video
  metaseg/mask_predictor.py
  requirements.txt
Labels: enhancement

#36 add output_path parameter
  metaseg/mask_predictor.py
  metaseg/utils/data_utils.py
Labels: enhancement

#38 remove predict function
  README.md
  metaseg/__init__.py
  metaseg/mask_predictor.py
  metaseg/sahi_predict.py
  metaseg/utils/__init__.py
  metaseg/utils/data_utils.py
Labels: documentation, enhancement

#39 Add return to load_model function
  README.md
  metaseg/__init__.py
  metaseg/mask_predictor.py
  metaseg/sahi_predict.py
  metaseg/utils/data_utils.py
Labels: bug, documentation, enhancement

#44 Update save
  metaseg/__init__.py
  metaseg/mask_predictor.py
  metaseg/sahi_predict.py
Labels: bug

#47 update web demo
  metaseg/__init__.py
  metaseg/mask_predictor.py
  metaseg/sahi_predict.py
  metaseg/webapp/app.py
  metaseg/webapp/demo.py
  requirements.txt
Labels: bug, documentation, enhancement

#56 add falai(server) support
  README.md
  metaseg/__init__.py
  metaseg/falai_demo.py
  metaseg/mask_predictor.py
  metaseg/utils/data_utils.py
Labels: documentation, enhancement

#57 add manuel mask for server
  README.md
  metaseg/__init__.py
  metaseg/falai_demo.py
  metaseg/mask_predictor.py
  requirements.txt
Labels: documentation, enhancement

#58 update version
  metaseg/__init__.py
  metaseg/falai_demo.py
Labels: bug, documentation
